# Generated by Django 5.1.3 on 2024-12-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('hierarchy_level', models.IntegerField(blank=True, null=True)),
                ('avatar_id', models.IntegerField(blank=True, null=True)),
                ('subtask', models.BooleanField(default=False)),
                ('project_scope', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Issue Type',
                'verbose_name_plural': 'Issue Types',
            },
        ),
    ]
